local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 5.0
   publish_frequency: 2.0
   width: 4.0
   height: 4.0
   resolution: 0.05
   static_map: false
   rolling_window: true
   plugins:
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}
